[package]
name = "TUW-EP"
version = "0.1.0"
edition = "2024"

[dependencies]
smallvec = { version = "1.13", features = [
    "const_generics",
    "const_new",
    "may_dangle",
    "union",
    "specialization",
] }
mimalloc = "0.1.43"
memmap2 = "0.9"
